### ISSUE TITLE
Add-On breaks Media path

### ISSUE THREAD

**Issue by JSchmidmaier** [Geta/EpiCategories#1]
After adding EpiCategories, the path to global assets is broken. Instead of rendering something like "globalAssets/.." it is rendering the culture and picture name, e.g. "/en/us/picture.png" instead of "/globalassets/picture.png"

**Comment by saintjon** [comment]
+1

**Comment by Codecamv** [comment]
+1

**Comment by ScottReed** [comment]
+1

**Comment by ScottReed** [comment]
FYI @saintjon @JSchmidmaier @Codecamv using version 1.0.5 works without the issue

**Comment by MattisOlsson** [comment]
Sorry for the delay. Been on vacation. ;) I'll take a look at the issue ASAP.

**Comment by MattisOlsson** [comment]
I will create a new package and upload it to Episerver NuGet. Should be available in the next few days.
