### ISSUE TITLE
AllowedTypes

### ISSUE THREAD

**Issue by Drol** [Geta/EpiCategories#14]
If I have a property like this.

```
[Categories]
[Display(Name = "Ämnen", Description = "Ämnen", Order = 11)]
[AllowedTypes(typeof(SubjectCategory))]
public virtual IList<ContentReference> Subjects { get; set; }
```

And have a tree with categories like this:
-Marketing (SubjectCategory)
-IT (AnotherCategory)
--Kommunication (SubjectCategory)
--Issues (SubjectCategory)
--Projects (SubjectCategory)

IT won't show up and SubjectCategories under it won't show up. Only Marketing.

Is there a way to solve this? Or is it a bug?

**Comment by MattisOlsson** [comment]
This was not supported previously but now it is. I just uploaded version 1.2.7 to Episerver NuGet feed so it should be available in the next few days.

**Comment by Drol** [comment]
Thanks, it works perfectly now :-)
