### ISSUE TITLE
Hide default Episerver Category should be optional

### ISSUE THREAD

**Issue by adnanzameer** [Geta/EpiCategories#17]
Hide default Episerver Category should be optional instead of this package do it for you. Its a major problem on the existing site which uses Episerver categories and hiding the category property confuses the editors when the migration is still in progress.

**Comment by MattisOlsson** [comment]
Good input. I'll add an app setting to disable the hiding since I want it to be opt-out.

**Comment by MattisOlsson** [comment]
Btw, this is open source software so you could always fork and create a pull request. ;)

**Comment by MattisOlsson** [comment]
I just pushed this and uploaded version 1.2.8 to Episerver nuget feed. Should be available in the next few days.
