### ISSUE TITLE
Setting to hide category in LinkModel dialog

### ISSUE THREAD

**Issue by Drol** [Geta/EpiCategories#20]
We don't want editors to be able to create links to categories. Would it be ok to add a setting to hide it?
![image](https://user-images.githubusercontent.com/362191/64765459-76416380-d544-11e9-9c94-0a4adace7247.png)

Should be able to do that by checking the setting in CategoryContentRepositoryDescriptor right?

```
        public override IEnumerable<Type> LinkableTypes => new[]
        {
            typeof (CategoryData)
        };
```

**Comment by MattisOlsson** [comment]
This is now implemented. I will update changelog, create new version and upload it to Episerver Nuget feed.

**Comment by Drol** [comment]
Awesome :-)
