### ISSUE TITLE
Page freezing while loading a large number of tags

### ISSUE THREAD

**Issue by mmbonthu** [Geta/EpiCategories#41]
Is it possible to include some kind of caching here? Some of our content editors are not able to load these categories as the page just freezes when the category tree is clicked.  Cheers

**Comment by MattisOlsson** [comment]
Hi,

I'm sorry for the very late reply. You have probably figured something out already, but here is some kind of explanation/recommendation:

Official APIs are used for fetching content and it's automatically cached. If you need to add additional caching you can use the decorator pattern to achieve that.

Optimizely official guidelines to structure content in groups/folders applies for this plugin as well. The UI does not handle a very large flat structure well. So the recommendation is to group your categories. You can set IsSelectable=false on the container categories if you do not want them to be selectable.

You can also create a dedicated container/folder category like this:

```
[ContentType]
public class ContainerCategory : CategoryData
{
    [ScaffoldColumn(false)] // Do not render this property
    public override bool IsSelectable { get; set; }

    public override void SetDefaultValues(ContentType contentType)
    {
        base.SetDefaultValues(contentType);
        IsSelectable = false;
    }
}
```
