### ISSUE TITLE
Update to be compatible for .NET 5.0 CMS 12

### ISSUE THREAD

**Issue by GeekInTheNorth** [Geta/EpiCategories#44]
Geta/EpiCategories is a popular module and has been implemented within a number of builds and has been requested by clients looking to my Agency for new builds.  We are aiming for all new builds to be built upon Optimizely CMS 12 and would like to see this package updated to match that target framework.

**Comment by JayWilk** [comment]
Indeed this is an issue for us as well, Geta categories is such a critical component to many CMS projects

**Comment by msarrafk** [comment]
Same here, just updated to latest version of Optimizely and can't use epicategories anymore.

**Comment by GeekInTheNorth** [comment]
> Same here, just updated to latest version of Optimizely and can't use epicategories anymore.

I believe it's moved here: https://github.com/Geta/geta-optimizely-categories

In a recent chat with the folks from Optimizely, I was told it worked. I've not yet tried it myself, but have two builds planned which will use it.

**Comment by msarrafk** [comment]
@GeekInTheNorth Thanks :-) Do you know how we can use it? It's not a package.

**Comment by GeekInTheNorth** [comment]
@msarrafk This might be more of a question for @MattisOlsson perhaps? or @marisks who is the owner of the CMS 12 version.

**Comment by marisks** [comment]
We have started on the upgrade but didn't have time to complete it. And yes, the new repo is here: https://github.com/Geta/geta-optimizely-categories

**Comment by MattisOlsson** [comment]
We are currently working on the upgrade so stay tuned for a v12 compatible version.

**Comment by valdisiljuconoks** [comment]
https://github.com/Geta/geta-optimizely-categories
