### ISSUE TITLE
NuGet package 1.2.1 doesn't have the config transform

### ISSUE THREAD

**Issue by alasvant** [Geta/EpiCategories#6]
Hi, the NuGet package 1.2.1 doesn't have the configuration transform. So the clientresources give 404 and you need to manually add the "add name="geta-epicategories" to the protected modules.

**Comment by MattisOlsson** [comment]
I will fix this ASAP.

**Comment by MattisOlsson** [comment]
I recently uploaded version 1.2.3 which closes this issue. Should be available in the next few days.

**Comment by MattisOlsson** [comment]
Thanks by the way! :)

**Comment by alasvant** [comment]
You are welcome :)
