### ISSUE TITLE
Update document for Geta.EpiCategories.Find

### ISSUE THREAD

**Issue by epidinhtran** [Geta/EpiCategories#7]
Could you please update the document for this package: Geta.EpiCategories.Find, right now I can't find anything explain how it works.

**Comment by MattisOlsson** [comment]
As of now it only contains a CMS search provider which means you can search for category content in the search bar in the CMS.
![cms-search-provider](https://user-images.githubusercontent.com/5345333/39695483-04649580-51eb-11e8-9d8e-2a350f647270.jpg)
